name: Push latest version
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@master
      - name: Add docker push secret
        run: 'umask 0077 && mkdir -p ~/.docker/ && echo "$DOCKER_AUTH_CONFIG" > ~/.docker/config.json'
        shell: bash
        env:
          DOCKER_AUTH_CONFIG: ${{secrets.DOCKER_AUTH_CONFIG}}
      - name: Publish latest tag to registry
        run: |
          docker build -t capihcloud/hcloud-cloud-controller-manager:latest .
          docker push capihcloud/hcloud-cloud-controller-manager:latest
